apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      derivedFields:
        - name: traceID
          matcherRegex: '"trace_id":"([^"]+)"'
          url: '$${__value.raw}'
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: 1h
        spanEndTimeShift: 1h
        filterByTraceID: true
        filterBySpanID: true
        tags: ["service.name", "http.method", "http.url"]
      serviceMap:
        datasourceUid: mimir
      nodeGraph:
        enabled: true

  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    uid: mimir
    jsonData:
      httpMethod: POST
      manageAlerts: false
      prometheusType: Mimir
      prometheusVersion: 2.11.0
      cacheLevel: 'High'
      incrementalQuerying: true
      incrementalQueryOverlapWindow: 10m
